#!/usr/bin/env python3
"""README.TXT desktop icon for JobDesk 2000: three pixel-art directions drawn on a 32 x 32 grid.

Each icon is a hand-placed pixel map (one character per pixel) turned into an SVG of crisp rectangles, so it stays
sharp at 64 px on the desktop and at 32 px in the taskbar, like the other desktop icons. No filters, no gradients.

    python3 design/readme-icon/make_icons.py   ->  design/readme-icon/out/*.svg, *.png, overview.png
"""
import os
import subprocess
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
EXISTING = os.path.join(HERE, "..", "..", "public", "assets", "icons")

PALETTE = {
    "K": "#2b2150",  # outline ink
    "W": "#ffffff",  # paper
    "P": "#efeafc",  # paper shade
    "S": "#cfc4ef",  # deeper shade
    "L": "#9a8ac8",  # text lines
    "R": "#e86aa6",  # pink line
    "Y": "#ffcc3d",  # star
    "O": "#e3961c",  # star shade
    "H": "#fff4b8",  # star highlight
    "V": "#7d6bc4",  # lavender body
    "D": "#5b4a9e",  # lavender shade
    "M": "#c9cde0",  # metal
    "N": "#8d92ad",  # metal shade
    "G": "#5bc98d",  # mint
}

# A: a page of notes with a folded corner and the fairy's star sticker
PAGE = """
................................
................................
.....KKKKKKKKKKKKKKKKK..........
.....KWWWWWWWWWWWWWWWKK.........
.....KWWWWWWWWWWWWWWWKPK........
.....KWWWWWWWWWWWWWWWKPPK.......
.....KWWLLLLLLLLLLWWWKPPPK......
.....KWWWWWWWWWWWWWWWKKKKKK.....
.....KWWLLLLLLLLWWWWWWWWWWK.....
.....KWWWWWWWWWWWWWWWWWWWPK.....
.....KWWRRRRRRRRRRRRRWWWWPK.....
.....KWWWWWWWWWWWWWWWWWWWPK.....
.....KWWLLLLLLLLLLLLLLWWWPK.....
.....KWWWWWWWWWWWWWWWWWWWPK.....
.....KWWLLLLLLLLLLLWWWWWWPK.....
.....KWWWWWWWWWWWWWWWWWWWPK.....
.....KWWLLLLLLLLLLLLLLWWWPK.....
.....KWWWWWWWWWWWWWWWWWWWPK.....
.....KWWLLLLLLLLLWWWWWWWWPK.....
.....KWWWWWWWWWWWWWWWWWWWPK.....
.....KWWLLLLLLLLLLLLWWWKKPK.....
.....KWWWWWWWWWWWWWWWWKYYKK.....
.....KWWLLLLLLLWWWWWWKYHYYKK....
.....KWWWWWWWWWWWWKKKYYHYYYKKK..
.....KWWWWWWWWWWWWKYYYHHYYYYYK..
.....KPPPPPPPPPPPPPKYYYYYYYYOK..
.....KPPPPPPPPPPPPPPKOYYYYYOK...
.....KKKKKKKKKKKKKKKKYYOYOYYK...
...................KYOK.KOYK....
...................KOK...KOK....
...................KK.....KK....
................................
"""

# B: a Y2K floppy disk whose label is a little page of notes
FLOPPY = """
................................
................................
....KKKKKKKKKKKKKKKKKKKKKKKK....
....KVVVVKMMMMMMMMMMMMKVVVVK....
....KVVVVKMMMMNNNMMMMMKVVVVK....
....KVVVVKMMMMNKNMMMMMKVVVVK....
....KVVVVKMMMMNKNMMMMMKVVVVK....
....KVVVVKMMMMNKNMMMMMKVVVVK....
....KVVVVKMMMMNNNMMMMMKVVVVK....
....KVVVVKNNNNNNNNNNNNKVVVVK....
....KVVVVVKKKKKKKKKKKKVVVVVK....
....KVVVVVVVVVVVVVVVVVVVVVVK....
....KVVKKKKKKKKKKKKKKKKKKVVK....
....KVKWWWWWWWWWWWWWWWWWWKVK....
....KVKWWRRRRRRRRRRRRRRWWKVK....
....KVKWWWWWWWWWWWWWWWWWWKVK....
....KVKWWLLLLLLLLLLLWWWWWKVK....
....KVKWWWWWWWWWWWWWWWWWWKVK....
....KVKWWLLLLLLLLLLLLLWYWKVK....
....KVKWWWWWWWWWWWWWWWYYYKVK....
....KVKWWLLLLLLLLLLWWWWYWKVK....
....KVKWWWWWWWWWWWWWWWWWWKVK....
....KVKWWLLLLLLLLLLLLWWWWKVK....
....KVKWWWWWWWWWWWWWWWWWWKVK....
....KVKPPPPPPPPPPPPPPPPPPKVK....
....KDKKKKKKKKKKKKKKKKKKKKDK....
....KDDDDDDDDDDDDDDDDDDDDDDK....
....KKKKKKKKKKKKKKKKKKKKKKKK....
................................
................................
................................
................................
"""

# C: a spiral notebook with a big question mark: "how does this work?"
NOTEBOOK = """
................................
................................
.......K..K..K..K..K..K.........
......KMK.KMK.KMK.KMK.KMK.......
.....KKNKKKNKKKNKKKNKKKNKKKK....
.....KWWNWWWNWWWNWWWNWWWNWWK....
.....KWWWWWWWWWWWWWWWWWWWWWK....
.....KWWWWWWWWWWWWWWWWWWWWPK....
.....KWWWWWWWWKKKKKKWWWWWWPK....
.....KWWWWWWWKVVVVVVKWWWWWPK....
.....KWWWWWWKVVKKKKVVKWWWWPK....
.....KWWWWWWKVKWWWWKVKWWWWPK....
.....KWWWWWWWKKWWWWKVKWWWWPK....
.....KWWWWWWWWWWWWKVVKWWWWPK....
.....KWWWWWWWWWWWKVVKWWWWWPK....
.....KWWWWWWWWWWKVVKWWWWWWPK....
.....KWWWWWWWWWWKVKWWWWWWWPK....
.....KWWWWWWWWWWKVKWWWWWWWPK....
.....KWWWWWWWWWWWKWWWWWWWWPK....
.....KWWWWWWWWWWKKKWWWWWWWPK....
.....KWWWWWWWWWKVVVKWWWWWWPK....
.....KWWWWWWWWWKVVVKWWWWWWPK....
.....KWWWWWWWWWWKKKWWWWWWWPK....
.....KWWLLLLLLLLLLLLLLLLWWPK....
.....KWWWWWWWWWWWWWWWWWWWWPK....
.....KWWRRRRRRRRRRRRRRWWWWPK....
.....KPPPPPPPPPPPPPPPPPPPPPK....
.....KKKKKKKKKKKKKKKKKKKKKKK....
................................
................................
................................
................................
"""



def put(art, cells):
    """Sets single pixels: cells = [(x, y, char)]."""
    grid = [list(line) for line in rows(art)]
    for x, y, ch in cells:
        grid[y][x] = ch
    return "\n".join("".join(line) for line in grid) + "\n"


def notebook_with_depth(art):
    """The notebook gets the lavender edge of its cover (right and bottom) and a little fairy sparkle by the "?"."""
    cells = []
    for y in range(6, 28):
        cells += [(28, y, "V"), (29, y, "K")]
    for x in range(7, 29):
        cells += [(x, 28, "V" if x < 28 else "D"), (x, 29, "K")]
    cells += [(28, 27, "D"), (28, 28, "D"), (29, 28, "K"), (29, 5, "K"), (28, 5, "K"), (6, 29, "K"), (6, 28, "K")]
    cells += [(22, 6, "Y"), (21, 7, "Y"), (22, 7, "H"), (23, 7, "Y"), (22, 8, "O")]
    cells += [(13, 9, "W"), (14, 9, "W")]  # a highlight in the curl of the question mark
    return put(art, cells)


def designs():
    return {"a-page": PAGE, "b-floppy": FLOPPY, "c-notebook": notebook_with_depth(NOTEBOOK)}


def rows(art):
    lines = [line for line in art.strip("\n").split("\n")]
    assert len(lines) == 32, (len(lines))
    for i, line in enumerate(lines):
        assert len(line) == 32, (i, len(line), line)
    return lines


def to_svg(art, size=64):
    rects = []
    for y, line in enumerate(rows(art)):
        x = 0
        while x < 32:
            ch = line[x]
            if ch == ".":
                x += 1
                continue
            run = 1
            while x + run < 32 and line[x + run] == ch:
                run += 1
            rects.append(f'<rect x="{x}" y="{y}" width="{run}" height="1" fill="{PALETTE[ch]}"/>')
            x += run
    body = "".join(rects)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="{size}" height="{size}" '
            f'shape-rendering="crispEdges">{body}</svg>\n')


def render(svg_path, png_path, size):
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), "-o", png_path, svg_path], check=True)


def overview(names):
    existing = ["messenger", "stats", "vacancies", "fairy", "about", "valya"]
    grounds = [(190, 225, 245, 255), (26, 14, 56, 255)]
    cell = 150
    width = cell * (len(existing) + len(names)) + 40
    sheet = Image.new("RGBA", (width, cell * 4 + 20), (255, 255, 255, 255))
    for g, ground in enumerate(grounds):
        for scale_row, size in enumerate([64, 32]):
            top = (g * 2 + scale_row) * cell + 10
            band = Image.new("RGBA", (width, cell), ground)
            sheet.alpha_composite(band, (0, top))
            icons = [Image.open(os.path.join(EXISTING, n + ".png")).convert("RGBA") for n in existing]
            icons += [Image.open(os.path.join(OUT, n + "-64.png")).convert("RGBA") for n in names]
            for i, icon in enumerate(icons):
                shown = icon.resize((size, size), Image.LANCZOS if size < 64 else Image.NEAREST)
                shown = shown.resize((size * 2, size * 2), Image.NEAREST)  # magnified 2x to judge the pixels
                x = 20 + i * cell + (cell - size * 2) // 2
                sheet.alpha_composite(shown, (x, top + (cell - size * 2) // 2))
    sheet.save(os.path.join(OUT, "overview.png"))


def main():
    os.makedirs(OUT, exist_ok=True)
    for name, art in designs().items():
        svg_path = os.path.join(OUT, name + ".svg")
        with open(svg_path, "w") as f:
            f.write(to_svg(art))
        for size in (64, 32):
            render(svg_path, os.path.join(OUT, f"{name}-{size}.png"), size)
    overview(list(designs()))


if __name__ == "__main__":
    main()
